# Postgres DB configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tulip
    username: apollo
    password: pass@123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true
